// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(InternshipDbContext))]
    partial class InternshipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Skype")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DAL.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RegDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Skype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialisation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("DAL.Models.CandidateSandbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidateID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SandboxID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateID");

                    b.HasIndex("SandboxID");

                    b.ToTable("CandidatesSandboxes");
                });

            modelBuilder.Entity("DAL.Models.EmployeeStack", b =>
                {
                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("StackID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID", "StackID");

                    b.HasIndex("StackID");

                    b.ToTable("EmployeesStacks");
                });

            modelBuilder.Entity("DAL.Models.InternshipTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InternshipTeams");
                });

            modelBuilder.Entity("DAL.Models.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidateID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("DAL.Models.InterviewResult", b =>
                {
                    b.Property<int>("InterviewID")
                        .HasColumnType("int");

                    b.Property<int>("TopicID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("InterviewID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("InterviewResults");
                });

            modelBuilder.Entity("DAL.Models.Sandbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Sandbox");
                });

            modelBuilder.Entity("DAL.Models.Stack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stacks");
                });

            modelBuilder.Entity("DAL.Models.TeamMentor", b =>
                {
                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID", "TeamID");

                    b.ToTable("TeamsMentors");
                });

            modelBuilder.Entity("DAL.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("DAL.Models.TopicStack", b =>
                {
                    b.Property<int>("StackID")
                        .HasColumnType("int");

                    b.Property<int>("TopicID")
                        .HasColumnType("int");

                    b.HasKey("StackID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("TopicsStacks");
                });

            modelBuilder.Entity("DAL.SandboxTeam", b =>
                {
                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<int>("CandidateSandboxID")
                        .HasColumnType("int");

                    b.HasKey("TeamID", "CandidateSandboxID");

                    b.HasIndex("CandidateSandboxID");

                    b.ToTable("SandboxTeam");
                });

            modelBuilder.Entity("DAL.Models.CandidateSandbox", b =>
                {
                    b.HasOne("DAL.Models.Candidate", "Candidate")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Sandbox", "Sandbox")
                        .WithMany("CandidateSandboxes")
                        .HasForeignKey("SandboxID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Sandbox");
                });

            modelBuilder.Entity("DAL.Models.EmployeeStack", b =>
                {
                    b.HasOne("DAL.Employee", "Employee")
                        .WithMany("EmployeeStack")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Stack", "Stack")
                        .WithMany("EmployeeStacks")
                        .HasForeignKey("StackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("DAL.Models.Interview", b =>
                {
                    b.HasOne("DAL.Models.Candidate", "Candidate")
                        .WithMany("Interviews")
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Employee", "Employee")
                        .WithMany("Interviews")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DAL.Models.InterviewResult", b =>
                {
                    b.HasOne("DAL.Models.Interview", "Interview")
                        .WithMany("InterviewResults")
                        .HasForeignKey("InterviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Topic", "Topics")
                        .WithMany("InterviewResults")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("DAL.Models.TeamMentor", b =>
                {
                    b.HasOne("DAL.Employee", "Employee")
                        .WithMany("TeamMentors")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.InternshipTeam", "InternshipTeam")
                        .WithMany("TeamMentors")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("InternshipTeam");
                });

            modelBuilder.Entity("DAL.Models.TopicStack", b =>
                {
                    b.HasOne("DAL.Models.Stack", "Stack")
                        .WithMany("TopicStacks")
                        .HasForeignKey("StackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Topic", "Topic")
                        .WithMany("TopicStacks")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stack");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DAL.SandboxTeam", b =>
                {
                    b.HasOne("DAL.Models.CandidateSandbox", "CandidateSandbox")
                        .WithMany("SandboxTeams")
                        .HasForeignKey("CandidateSandboxID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.InternshipTeam", "InternshipTeam")
                        .WithMany("SandboxTeams")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateSandbox");

                    b.Navigation("InternshipTeam");
                });

            modelBuilder.Entity("DAL.Employee", b =>
                {
                    b.Navigation("EmployeeStack");

                    b.Navigation("Interviews");

                    b.Navigation("TeamMentors");
                });

            modelBuilder.Entity("DAL.Models.Candidate", b =>
                {
                    b.Navigation("CandidateSandboxes");

                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("DAL.Models.CandidateSandbox", b =>
                {
                    b.Navigation("SandboxTeams");
                });

            modelBuilder.Entity("DAL.Models.InternshipTeam", b =>
                {
                    b.Navigation("SandboxTeams");

                    b.Navigation("TeamMentors");
                });

            modelBuilder.Entity("DAL.Models.Interview", b =>
                {
                    b.Navigation("InterviewResults");
                });

            modelBuilder.Entity("DAL.Models.Sandbox", b =>
                {
                    b.Navigation("CandidateSandboxes");
                });

            modelBuilder.Entity("DAL.Models.Stack", b =>
                {
                    b.Navigation("EmployeeStacks");

                    b.Navigation("TopicStacks");
                });

            modelBuilder.Entity("DAL.Models.Topic", b =>
                {
                    b.Navigation("InterviewResults");

                    b.Navigation("TopicStacks");
                });
#pragma warning restore 612, 618
        }
    }
}
